name: TTT
main: me.zabzabdoda.TTT.TTT
version: 1.0
api-version: 1.16
author: zabzabdoda
description: Trouble in Terrorist Town plugin
commands:
  ttt:
    description: Main command for Trouble in Terrorist Town.
    usage: |
           /ttt <start|join>
           Example: /ttt start - Starts the TTT game
  chat:
    description: switches chat rooms.
    usage: |
           /chat <global|traitor>
           Example: /chat traitor - switches to traitor chat.